package com.urlshortener.service;

import com.urlshortener.dto.CreateUrlRequest;
import com.urlshortener.dto.UrlResponse;
import com.urlshortener.entity.UrlMapping;
import com.urlshortener.exception.ShortCodeAlreadyExistsException;
import com.urlshortener.exception.UrlExpiredException;
import com.urlshortener.exception.UrlNotFoundException;
import com.urlshortener.repository.UrlMappingRepository;
import com.urlshortener.util.ShortCodeGenerator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * UrlShortenerServiceTest — Unit Tests for the Service Layer
 *
 * TESTING PHILOSOPHY:
 * Unit tests test a single class in complete ISOLATION.
 * We "mock" all dependencies so:
 *   - No real database needed
 *   - No Spring context needed
 *   - Tests run in milliseconds
 *   - We control exactly what dependencies return
 *
 * TOOLS USED:
 * - JUnit 5 (@Test, @BeforeEach, @DisplayName) — test framework
 * - Mockito (@Mock, @InjectMocks, when/verify) — mocking framework
 * - AssertJ (assertThat) — fluent assertion library (cleaner than assertEquals)
 *
 * @ExtendWith(MockitoExtension.class)
 *   Tells JUnit to use Mockito's extension, which:
 *   1. Creates mocks for @Mock fields
 *   2. Injects them into @InjectMocks
 *   Without this, @Mock and @InjectMocks don't work.
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("UrlShortenerService Unit Tests")
class UrlShortenerServiceTest {

    /**
     * @Mock — Creates a "fake" (mock) implementation of UrlMappingRepository.
     * All its methods return default values (null, 0, false) unless we tell it otherwise.
     * The real database is NEVER touched.
     */
    @Mock
    private UrlMappingRepository repository;

    /**
     * @Mock — Creates a fake ShortCodeGenerator.
     * We control what generate() returns in each test.
     */
    @Mock
    private ShortCodeGenerator shortCodeGenerator;

    /**
     * @InjectMocks — Creates a REAL UrlShortenerService instance.
     * Mockito automatically injects the @Mock objects above into it
     * (via constructor injection, matching types).
     */
    @InjectMocks
    private UrlShortenerService urlShortenerService;

    /**
     * @BeforeEach — Runs before EVERY @Test method.
     * Sets the baseUrl field (normally injected via @Value, which doesn't work without Spring).
     * ReflectionTestUtils.setField() injects a value into a private field using reflection.
     */
    @BeforeEach
    void setUp() {
        ReflectionTestUtils.setField(urlShortenerService, "baseUrl", "http://localhost:8080");
    }

    // ── Tests for createShortUrl() ─────────────────────────────────────────

    @Test
    @DisplayName("Should create short URL with auto-generated code when no custom code provided")
    void createShortUrl_AutoGeneratedCode_Success() {
        // ── ARRANGE (set up preconditions) ────────────────────────────────
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("https://www.example.com/very/long/url")
                .build();

        // Tell the mock: when generate() is called, return "abc123"
        when(shortCodeGenerator.generate()).thenReturn("abc123");

        // Tell the mock: "abc123" doesn't exist yet (so it's available)
        when(repository.existsByShortCode("abc123")).thenReturn(false);

        // Build the entity that the repository "saves" and returns
        UrlMapping savedMapping = UrlMapping.builder()
                .id(1L)
                .originalUrl("https://www.example.com/very/long/url")
                .shortCode("abc123")
                .clickCount(0L)
                .isActive(true)
                .createdAt(LocalDateTime.now())
                .build();

        // Tell the mock: when save() is called with ANY UrlMapping, return savedMapping
        when(repository.save(any(UrlMapping.class))).thenReturn(savedMapping);

        // ── ACT (call the method under test) ──────────────────────────────
        UrlResponse response = urlShortenerService.createShortUrl(request);

        // ── ASSERT (verify the results) ───────────────────────────────────
        assertThat(response).isNotNull();
        assertThat(response.getShortCode()).isEqualTo("abc123");
        assertThat(response.getOriginalUrl()).isEqualTo("https://www.example.com/very/long/url");
        assertThat(response.getShortUrl()).isEqualTo("http://localhost:8080/abc123");
        assertThat(response.getClickCount()).isEqualTo(0L);

        // Verify interactions: repository.save() was called exactly once
        verify(repository, times(1)).save(any(UrlMapping.class));
        // Verify the generator was called once
        verify(shortCodeGenerator, times(1)).generate();
    }

    @Test
    @DisplayName("Should use custom code when provided")
    void createShortUrl_CustomCode_Success() {
        // ARRANGE
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("https://www.example.com")
                .customCode("my-brand")
                .build();

        when(repository.existsByShortCode("my-brand")).thenReturn(false);

        UrlMapping savedMapping = UrlMapping.builder()
                .id(1L)
                .originalUrl("https://www.example.com")
                .shortCode("my-brand")
                .clickCount(0L)
                .isActive(true)
                .createdAt(LocalDateTime.now())
                .build();

        when(repository.save(any(UrlMapping.class))).thenReturn(savedMapping);

        // ACT
        UrlResponse response = urlShortenerService.createShortUrl(request);

        // ASSERT
        assertThat(response.getShortCode()).isEqualTo("my-brand");

        // CRITICAL: The generator should NEVER be called when a custom code is provided
        verify(shortCodeGenerator, never()).generate();
    }

    @Test
    @DisplayName("Should throw ShortCodeAlreadyExistsException when custom code is taken")
    void createShortUrl_CustomCodeAlreadyExists_ThrowsException() {
        // ARRANGE
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("https://www.example.com")
                .customCode("taken-code")
                .build();

        // Simulate: "taken-code" already exists in the DB
        when(repository.existsByShortCode("taken-code")).thenReturn(true);

        // ACT & ASSERT
        // assertThatThrownBy() passes if the lambda throws the expected exception
        assertThatThrownBy(() -> urlShortenerService.createShortUrl(request))
                .isInstanceOf(ShortCodeAlreadyExistsException.class)
                .hasMessageContaining("taken-code");

        // Verify save was NEVER called (we short-circuited before saving)
        verify(repository, never()).save(any());
    }

    // ── Tests for resolveUrl() ─────────────────────────────────────────────

    @Test
    @DisplayName("Should return original URL and increment click count")
    void resolveUrl_ValidCode_ReturnsOriginalUrl() {
        // ARRANGE
        String shortCode = "abc123";
        UrlMapping mapping = UrlMapping.builder()
                .id(1L)
                .originalUrl("https://www.example.com")
                .shortCode(shortCode)
                .clickCount(5L)
                .isActive(true)
                .expiresAt(null)  // no expiry
                .build();

        when(repository.findActiveByShortCode(shortCode)).thenReturn(Optional.of(mapping));
        // incrementClickCount returns void, so we don't need to stub it
        doNothing().when(repository).incrementClickCount(1L);

        // ACT
        String result = urlShortenerService.resolveUrl(shortCode);

        // ASSERT
        assertThat(result).isEqualTo("https://www.example.com");

        // Verify click count was incremented
        verify(repository, times(1)).incrementClickCount(1L);
    }

    @Test
    @DisplayName("Should throw UrlNotFoundException when short code doesn't exist")
    void resolveUrl_NonExistentCode_ThrowsNotFoundException() {
        // ARRANGE
        when(repository.findActiveByShortCode("ghost")).thenReturn(Optional.empty());

        // ACT & ASSERT
        assertThatThrownBy(() -> urlShortenerService.resolveUrl("ghost"))
                .isInstanceOf(UrlNotFoundException.class)
                .hasMessageContaining("ghost");

        // Click count should never be incremented for non-existent URLs
        verify(repository, never()).incrementClickCount(any());
    }

    @Test
    @DisplayName("Should throw UrlExpiredException when URL has expired")
    void resolveUrl_ExpiredUrl_ThrowsUrlExpiredException() {
        // ARRANGE
        UrlMapping expiredMapping = UrlMapping.builder()
                .id(1L)
                .originalUrl("https://www.example.com")
                .shortCode("expired")
                .isActive(true)
                // Set expiry to YESTERDAY (past date)
                .expiresAt(LocalDateTime.now().minusDays(1))
                .build();

        when(repository.findActiveByShortCode("expired")).thenReturn(Optional.of(expiredMapping));

        // ACT & ASSERT
        assertThatThrownBy(() -> urlShortenerService.resolveUrl("expired"))
                .isInstanceOf(UrlExpiredException.class)
                .hasMessageContaining("expired");

        verify(repository, never()).incrementClickCount(any());
    }

    @Test
    @DisplayName("Should work fine when URL has a future expiry date")
    void resolveUrl_FutureExpiryDate_Success() {
        // ARRANGE
        UrlMapping mapping = UrlMapping.builder()
                .id(1L)
                .originalUrl("https://www.example.com")
                .shortCode("notexpired")
                .isActive(true)
                // Set expiry to TOMORROW (future date = still valid)
                .expiresAt(LocalDateTime.now().plusDays(1))
                .build();

        when(repository.findActiveByShortCode("notexpired")).thenReturn(Optional.of(mapping));
        doNothing().when(repository).incrementClickCount(1L);

        // ACT
        String result = urlShortenerService.resolveUrl("notexpired");

        // ASSERT — should succeed, not throw
        assertThat(result).isEqualTo("https://www.example.com");
    }

    // ── Tests for getAllUrls() ─────────────────────────────────────────────

    @Test
    @DisplayName("Should return list of all URL responses")
    void getAllUrls_ReturnsAllMappings() {
        // ARRANGE
        UrlMapping m1 = UrlMapping.builder()
                .id(1L).originalUrl("https://a.com").shortCode("aaa111")
                .clickCount(10L).isActive(true).createdAt(LocalDateTime.now()).build();
        UrlMapping m2 = UrlMapping.builder()
                .id(2L).originalUrl("https://b.com").shortCode("bbb222")
                .clickCount(5L).isActive(true).createdAt(LocalDateTime.now()).build();

        when(repository.findAll()).thenReturn(List.of(m1, m2));

        // ACT
        List<UrlResponse> responses = urlShortenerService.getAllUrls();

        // ASSERT
        assertThat(responses).hasSize(2);
        assertThat(responses.get(0).getShortCode()).isEqualTo("aaa111");
        assertThat(responses.get(1).getShortCode()).isEqualTo("bbb222");
    }

    @Test
    @DisplayName("Should return empty list when no URLs exist")
    void getAllUrls_NoUrls_ReturnsEmptyList() {
        when(repository.findAll()).thenReturn(List.of());

        List<UrlResponse> responses = urlShortenerService.getAllUrls();

        assertThat(responses).isEmpty();
    }

    // ── Tests for deactivateUrl() ─────────────────────────────────────────

    @Test
    @DisplayName("Should deactivate an active URL")
    void deactivateUrl_ActiveUrl_SetsInactive() {
        // ARRANGE
        UrlMapping mapping = UrlMapping.builder()
                .id(1L)
                .originalUrl("https://example.com")
                .shortCode("toDelete")
                .isActive(true)
                .build();

        when(repository.findByShortCode("toDelete")).thenReturn(Optional.of(mapping));
        when(repository.save(any(UrlMapping.class))).thenReturn(mapping);

        // ACT
        urlShortenerService.deactivateUrl("toDelete");

        // ASSERT
        // Verify that isActive was set to false
        assertThat(mapping.getIsActive()).isFalse();
        // Verify save was called (to persist the change)
        verify(repository, times(1)).save(mapping);
    }

    @Test
    @DisplayName("Should throw UrlNotFoundException when deactivating non-existent URL")
    void deactivateUrl_NonExistent_ThrowsNotFoundException() {
        when(repository.findByShortCode("ghost")).thenReturn(Optional.empty());

        assertThatThrownBy(() -> urlShortenerService.deactivateUrl("ghost"))
                .isInstanceOf(UrlNotFoundException.class);

        verify(repository, never()).save(any());
    }
}
